version: "3.7"

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: ${MSSQL_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - D:\mssql\data:/var/opt/mssql/data
      - D:\temp\mssql:/var/opt/mssql/backup
    user: root
    ports:
      - 1433:1433
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGSQL_ROOT_PASSWORD}
    ports:
      - 5432:5432
    volumes: 
      - D:\pgsql\data:/var/lib/postgresql/data
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '8080:80'
      - '8081:81'
      - '4443:443'
    environment:
      DB_MYSQL_HOST: ${MYSQL_HOST}
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DB}
    volumes:
      - D:\nginx\data:/data
      - D:\letsencrypt\data:/etc/letsencrypt
  mysql:
    container_name: ${MYSQL_HOST}
    image: 'jc21/mariadb-aria:latest'
    volumes: 
      - D:\mysql\data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
